# Generated by Django 5.1.9 on 2025-06-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF certificate",
                null=True,
                upload_to="certificates/",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grade percentage (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="is_valid",
            field=models.BooleanField(
                default=True, help_text="Is this certificate still valid"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Course thumbnail image",
                null=True,
                upload_to="course_thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated time to complete this lesson",
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
            ),
        ),
    ]
