# Generated by Django 5.1.9 on 2025-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_certificate_certificate_pdf_certificate_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="certificate_pdf",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="is_valid",
        ),
        migrations.RemoveField(
            model_name="course",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/covers/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration (hours)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Free Course"),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price"
            ),
        ),
    ]
